# CI & CD workflow
name: CI/CD - Liquid.WebApi.Http.Extensions.Crud component for Liquid Application Framework

on:
  push:
    branches: [ main, releases/v2.X.X, releases/v6.X.X ]
    paths:
    - 'src/Liquid.WebApi.Http.Extensions.Crud/**'
    
  pull_request:
    branches: [ main, releases/** ]
    types: [opened, synchronize, reopened]
    paths:
    - 'src/Liquid.WebApi.Http.Extensions.Crud/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-reusable-build-workflow:
    uses: Avanade/Liquid-Application-Framework/.github/workflows/base-liquid-ci-and-cd.yml@main
    with:
      component_name: Liquid.WebApi.Http.Extensions.Crud
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN_HTTP_EXT_CRUD }}
      nuget_token: ${{ secrets.PUBLISH_TO_NUGET_ORG }}
